apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
      app: demo-voting-app
  template:
    metadata:
      name: db
      labels:
        name: db
        app: demo-voting-app

    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
